# Generated by Django 4.1.7 on 2023-03-11 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userformapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userform',
            name='birthdate',
        ),
    ]
