# Generated by Django 4.1.7 on 2023-03-12 06:56

from django.db import migrations, models
import userformapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('userformapp', '0002_remove_userform_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='phone_number',
            field=models.CharField(max_length=20, validators=[userformapp.models.validate_phone_number]),
        ),
    ]
